# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zsXfnvspK0IQypMVS3hnuytIyNYBz4Ix
"""

from chess_tournament import Player
import chess
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
import torch
import torch.nn.functional as F


class TransformerPlayer(Player):

    def __init__(self, name="MyPlayer"):
        super().__init__(name)
        model_name = "Mariyana0019/chess-tinyllama-ultimate"
        bnb_config = BitsAndBytesConfig(load_in_4bit=True)
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.tokenizer.pad_token = self.tokenizer.eos_token
        self.model = AutoModelForCausalLM.from_pretrained(
            model_name,
            quantization_config=bnb_config,
            device_map="auto"
        )
        self.move_history = []
        print(f"✅ {self.name} is ready!")

    def score_move(self, prompt, move):
        full_text = prompt + " " + move
        inputs = self.tokenizer(full_text, return_tensors="pt").to("cuda")
        prompt_inputs = self.tokenizer(prompt, return_tensors="pt").to("cuda")
        prompt_length = prompt_inputs["input_ids"].shape[1]
        with torch.no_grad():
            outputs = self.model(**inputs, labels=inputs["input_ids"])
            logits = outputs.logits[0, prompt_length-1:-1]
            labels = inputs["input_ids"][0, prompt_length:]
            loss = F.cross_entropy(logits, labels)
        return -loss.item()

    def piece_value(self, piece_type):
        return {chess.PAWN: 1, chess.KNIGHT: 3, chess.BISHOP: 3,
                chess.ROOK: 5, chess.QUEEN: 9, chess.KING: 100}.get(piece_type, 0)

    def would_hang_piece(self, board, move):
        board.push(move)
        our_color = not board.turn
        hanging = False
        for square in chess.SQUARES:
            piece = board.piece_at(square)
            if piece and piece.color == our_color:
                attackers = board.attackers(not our_color, square)
                defenders = board.attackers(our_color, square)
                if len(attackers) > len(defenders):
                    hanging = True
                    break
        board.pop()
        return hanging

    def is_good_trade(self, board, move):
        if not board.is_capture(move):
            return True
        captured = board.piece_at(move.to_square)
        attacker = board.piece_at(move.from_square)
        if captured and attacker:
            return self.piece_value(captured.piece_type) >= self.piece_value(attacker.piece_type)
        return True

    def get_move_bonus(self, board, move):
        bonus = 0.0

        # Reward captures weighted by piece value
        if board.is_capture(move):
            captured = board.piece_at(move.to_square)
            if captured:
                bonus += self.piece_value(captured.piece_type) * 0.5

        # Reward checks
        board.push(move)
        if board.is_check():
            bonus += 1.0
        board.pop()

        # Reward center control
        center = [chess.E4, chess.E5, chess.D4, chess.D5]
        extended = [chess.C3, chess.C4, chess.C5, chess.C6,
                    chess.D3, chess.D6, chess.E3, chess.E6,
                    chess.F3, chess.F4, chess.F5, chess.F6]
        if move.to_square in center:
            bonus += 0.5
        elif move.to_square in extended:
            bonus += 0.2

        # Reward castling
        piece = board.piece_at(move.from_square)
        if piece and piece.piece_type == chess.KING:
            if board.is_castling(move):
                bonus += 2.0

        # Penalize hanging pieces
        if self.would_hang_piece(board, move):
            bonus -= 2.0

        # Penalize repeated moves
        if move.uci() in self.move_history[-6:]:
            bonus -= 1.0

        return bonus

    def get_move(self, fen):
        board = chess.Board(fen)
        legal_moves = list(board.legal_moves)
        if not legal_moves:
            return None

        # Priority 1: Checkmate immediately
        for move in legal_moves:
            board.push(move)
            if board.is_checkmate():
                board.pop()
                return move.uci()
            board.pop()

        # Priority 2: Promote to queen
        for move in legal_moves:
            if move.promotion == chess.QUEEN:
                return move.uci()

        # Priority 3: Good captures only
        for move in legal_moves:
            if board.is_capture(move):
                captured = board.piece_at(move.to_square)
                if captured and self.piece_value(captured.piece_type) >= 3:
                    if self.is_good_trade(board, move):
                        if not self.would_hang_piece(board, move):
                            return move.uci()

        # Priority 4: Model score + bonuses
        prompt = f"[INST] Chess move for: {fen} [/INST]"
        best_move = None
        best_score = float('-inf')

        for move in legal_moves:
            model_score = self.score_move(prompt, move.uci())
            bonus = self.get_move_bonus(board, move)
            total = model_score + bonus
            if total > best_score:
                best_score = total
                best_move = move.uci()

        if best_move:
            self.move_history.append(best_move)

        return best_move