# -*- coding: utf-8 -*-
"""chess_player_clean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8aWh7PTtZdR7SdygQL-bLpy0ng9Di1f

## Step 1 — Setup
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/bylinina/chess_exam.git
# %cd /content/chess_exam
!pip install -e .
!pip install transformers accelerate bitsandbytes peft trl datasets chess requests zstandard

"""## Step 2 — Imports"""

from chess_tournament import Game, Player, RandomPlayer, EnginePlayer
import chess
import chess.pgn
from typing import Optional
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model
from trl import SFTTrainer, SFTConfig
from datasets import Dataset
from huggingface_hub import login
import torch
import torch.nn.functional as F
import pandas as pd
import os
import io
import zstandard as zstd
import requests
from google.colab import files

"""## Step 3 — Log in to HuggingFace"""

login()

"""## Step 4 — Set RapidAPI key for Stockfish"""

from getpass import getpass
os.environ["RAPIDAPI_KEY"] = getpass("Paste your RapidAPI key:")

"""## Step 5 — Generate Stockfish training data (20 games)"""

engine_strong = EnginePlayer("Stockfish-Strong", blunder_rate=0.0, ponder_rate=0.05)

os.chdir('/content')
for i in range(20):
    game = Game(engine_strong, engine_strong, max_half_moves=80)
    game.play(log_moves=True, log_to_file=f'/content/stockfish_game_{i}.csv')
    print(f"Game {i+1}/20 done")

all_files = [f for f in os.listdir('/content') if f.startswith('stockfish_game_')]
dfs = [pd.read_csv(f'/content/{f}') for f in all_files]
combined = pd.concat(dfs, ignore_index=True)
combined.to_csv('/content/all_chess_data.csv', index=False)
print(f"✅ Stockfish data saved! Total moves: {len(combined)}")
files.download('/content/all_chess_data.csv')

"""## Step 6 — Download Lichess data"""

url = "https://database.lichess.org/standard/lichess_db_standard_rated_2013-01.pgn.zst"
print("Downloading lichess games...")
response = requests.get(url, stream=True)
with open('/content/lichess.pgn.zst', 'wb') as f:
    downloaded = 0
    for chunk in response.iter_content(chunk_size=8192):
        f.write(chunk)
        downloaded += len(chunk)
        if downloaded % (1024*1024) == 0:
            print(f"Downloaded: {downloaded // (1024*1024)} MB")
print("✅ Download done!")

"""## Step 7 — Extract winning moves from Lichess"""

rows = []
with open('/content/lichess.pgn.zst', 'rb') as f:
    dctx = zstd.ZstdDecompressor()
    with dctx.stream_reader(f) as reader:
        text_stream = io.TextIOWrapper(reader, encoding='utf-8')
        while len(rows) < 5000:
            game = chess.pgn.read_game(text_stream)
            if game is None:
                break
            result = game.headers.get("Result", "*")
            board = game.board()
            for move in game.mainline_moves():
                if result == "1-0" and board.turn == chess.WHITE:
                    rows.append({'fen_before': board.fen(), 'move': move.uci()})
                elif result == "0-1" and board.turn == chess.BLACK:
                    rows.append({'fen_before': board.fen(), 'move': move.uci()})
                board.push(move)

df_lichess = pd.DataFrame(rows)
print(f"✅ Extracted {len(df_lichess)} winning moves from Lichess!")

"""## Step 8 — Combine Stockfish + Lichess data"""

# Load Stockfish data and keep only good moves
df_stockfish = pd.read_csv('/content/all_chess_data.csv')
good_moves = df_stockfish[df_stockfish['fallback'] == False][['fen_before', 'move']]
print(f"Stockfish good moves: {len(good_moves)}")

# Combine both datasets
combined_df = pd.concat([good_moves, df_lichess], ignore_index=True)
print(f"Lichess winning moves: {len(df_lichess)}")
print(f"Total combined: {len(combined_df)}")

# Format for training
def format_row(row):
    return {"text": f"[INST] Chess move for: {row['fen_before']} [/INST] {row['move']}"}

formatted = combined_df.apply(format_row, axis=1).tolist()
formatted_df = pd.DataFrame(formatted)
dataset_combined = Dataset.from_pandas(formatted_df)

print(f"\n✅ Dataset ready: {len(dataset_combined)} examples")
print("Example:", dataset_combined[0]['text'])

"""## Step 9 — Load TinyLlama and apply LoRA"""

base_model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
bnb_config = BitsAndBytesConfig(load_in_4bit=True)

tokenizer = AutoTokenizer.from_pretrained(base_model_name)
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    base_model_name,
    quantization_config=bnb_config,
    device_map="auto"
)

lora_config = LoraConfig(r=16, lora_alpha=32, lora_dropout=0.05, bias="none", task_type="CAUSAL_LM")
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()
print("✅ Model ready for training!")

"""## Step 10 — Train the model (~40-50 mins)"""

training_args = SFTConfig(
    output_dir="/content/chess_model_combined",
    num_train_epochs=5,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=4,
    learning_rate=2e-4,
    bf16=True,
    logging_steps=20,
    save_steps=100,
)

trainer = SFTTrainer(
    model=model,
    train_dataset=dataset_combined,
    args=training_args,
)

print("✅ Starting training...")
trainer.train()
print("✅ Training done!")

"""## Step 11 — Merge and push to HuggingFace
⚠️ Replace `your-username` with your actual HuggingFace username!
"""

merged_model = trainer.model.merge_and_unload()
print("✅ Model merged!")

hf_name = "Mariyana0019/chess-tinyllama-combined"  # ⚠️ CHANGE THIS
merged_model.push_to_hub(hf_name)
tokenizer.push_to_hub(hf_name)
print(f"✅ Model saved to HuggingFace: {hf_name}")

"""## Step 12 — Build your final TransformerPlayer
⚠️ Replace `your-username` with your actual HuggingFace username!
"""

class TransformerPlayer(Player):

    def __init__(self, name="MyPlayer"):
        super().__init__(name)

        model_name = "Mariyana0019/chess-tinyllama-combined"  # ⚠️ CHANGE THIS
        bnb_config = BitsAndBytesConfig(load_in_4bit=True)

        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.tokenizer.pad_token = self.tokenizer.eos_token
        self.model = AutoModelForCausalLM.from_pretrained(
            model_name,
            quantization_config=bnb_config,
            device_map="auto"
        )
        print(f"✅ {self.name} is ready!")

    def score_move(self, prompt, move):
        full_text = prompt + " " + move
        inputs = self.tokenizer(full_text, return_tensors="pt").to("cuda")
        prompt_inputs = self.tokenizer(prompt, return_tensors="pt").to("cuda")
        prompt_length = prompt_inputs["input_ids"].shape[1]
        with torch.no_grad():
            outputs = self.model(**inputs, labels=inputs["input_ids"])
            logits = outputs.logits[0, prompt_length-1:-1]
            labels = inputs["input_ids"][0, prompt_length:]
            loss = F.cross_entropy(logits, labels)
        return -loss.item()

    def get_move_bonus(self, board, move):
        bonus = 0.0
        if board.is_capture(move):
            bonus += 1.0
        board.push(move)
        if board.is_check():
            bonus += 0.5
        board.pop()
        center = ['e4', 'e5', 'd4', 'd5']
        if chess.square_name(move.to_square) in center:
            bonus += 0.3
        return bonus

    def get_move(self, fen):
        board = chess.Board(fen)
        legal_moves = list(board.legal_moves)
        if not legal_moves:
            return None
        prompt = f"[INST] Chess move for: {fen} [/INST]"
        best_move = None
        best_score = float('-inf')
        for move in legal_moves:
            model_score = self.score_move(prompt, move.uci())
            bonus = self.get_move_bonus(board, move)
            total_score = model_score + bonus
            if total_score > best_score:
                best_score = total_score
                best_move = move.uci()
        return best_move

my_player = TransformerPlayer("MyPlayer")

"""## Step 13 — Test your player"""

wins, draws, losses, total_fallbacks = 0, 0, 0, 0

for i in range(5):
    r = Game(my_player, RandomPlayer("Random"), max_half_moves=300).play()
    points = r[1]["MyPlayer"]
    fb = r[2].get("MyPlayer", 0)
    total_fallbacks += fb
    if points == 1.0:
        wins += 1
    elif points == 0.5:
        draws += 1
    else:
        losses += 1
    print(f"Game {i+1}: {'WIN' if points==1.0 else 'DRAW' if points==0.5 else 'LOSS'}  |  fallbacks: {fb}")

print(f"\nSummary: {wins}W / {draws}D / {losses}L  |  Total fallbacks: {total_fallbacks}")

wins, draws, losses, total_fallbacks = 0, 0, 0, 0

for i in range(10):
    r = Game(my_player, RandomPlayer("Random"), max_half_moves=300).play()
    points = r[1]["MyPlayer"]
    fb = r[2].get("MyPlayer", 0)
    total_fallbacks += fb
    if points == 1.0:
        wins += 1
    elif points == 0.5:
        draws += 1
    else:
        losses += 1
    print(f"Game {i+1}: {'WIN' if points==1.0 else 'DRAW' if points==0.5 else 'LOSS'}  |  fallbacks: {fb}")

print(f"\nSummary: {wins}W / {draws}D / {losses}L  |  Total fallbacks: {total_fallbacks}")



"""new strategy"""

class TransformerPlayer(Player):

    def __init__(self, name="MyPlayer"):
        super().__init__(name)

        model_name = "Mariyana0019/chess-tinyllama-combined"  # ⚠️ CHANGE THIS
        bnb_config = BitsAndBytesConfig(load_in_4bit=True)

        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.tokenizer.pad_token = self.tokenizer.eos_token
        self.model = AutoModelForCausalLM.from_pretrained(
            model_name,
            quantization_config=bnb_config,
            device_map="auto"
        )
        print(f"✅ {self.name} is ready!")

    def score_move(self, prompt, move):
        full_text = prompt + " " + move
        inputs = self.tokenizer(full_text, return_tensors="pt").to("cuda")
        prompt_inputs = self.tokenizer(prompt, return_tensors="pt").to("cuda")
        prompt_length = prompt_inputs["input_ids"].shape[1]
        with torch.no_grad():
            outputs = self.model(**inputs, labels=inputs["input_ids"])
            logits = outputs.logits[0, prompt_length-1:-1]
            labels = inputs["input_ids"][0, prompt_length:]
            loss = F.cross_entropy(logits, labels)
        return -loss.item()

    def piece_value(self, board, move):
        # How valuable is the piece we're capturing?
        piece = board.piece_at(move.to_square)
        if piece is None:
            return 0
        values = {
            chess.PAWN: 1,
            chess.KNIGHT: 3,
            chess.BISHOP: 3,
            chess.ROOK: 5,
            chess.QUEEN: 9,
            chess.KING: 100
        }
        return values.get(piece.piece_type, 0)

    def get_move(self, fen):
        board = chess.Board(fen)
        legal_moves = list(board.legal_moves)

        if not legal_moves:
            return None

        # Priority 1: Checkmate — instant win, take it immediately!
        for move in legal_moves:
            board.push(move)
            if board.is_checkmate():
                board.pop()
                return move.uci()
            board.pop()

        # Priority 2: Best capture (take the most valuable piece)
        captures = [(move, self.piece_value(board, move))
                    for move in legal_moves if board.is_capture(move)]
        if captures:
            best_capture = max(captures, key=lambda x: x[1])
            if best_capture[1] >= 3:  # only take if it's worth at least a knight
                return best_capture[0].uci()

        # Priority 3: Give check
        for move in legal_moves:
            board.push(move)
            if board.is_check():
                board.pop()
                return move.uci()
            board.pop()

        # Priority 4: Use model score for everything else
        prompt = f"[INST] Chess move for: {fen} [/INST]"
        best_move = None
        best_score = float('-inf')
        for move in legal_moves:
            score = self.score_move(prompt, move.uci())
            if score > best_score:
                best_score = score
                best_move = move.uci()

        return best_move

my_player = TransformerPlayer("MyPlayer")

wins, draws, losses, total_fallbacks = 0, 0, 0, 0

for i in range(5):
    r = Game(my_player, RandomPlayer("Random"), max_half_moves=300).play()
    points = r[1]["MyPlayer"]
    fb = r[2].get("MyPlayer", 0)
    total_fallbacks += fb

    if points == 1.0:
        wins += 1
    elif points == 0.5:
        draws += 1
    else:
        losses += 1

    print(f"Game {i+1}: {'WIN' if points==1.0 else 'DRAW' if points==0.5 else 'LOSS'}  |  fallbacks: {fb}")

print(f"\nSummary: {wins}W / {draws}D / {losses}L  |  Total fallbacks: {total_fallbacks}")